# Nacos 配置上传元数据清单
metadata:
- appName: ''
  dataId: application-actuator.yml
  desc: Actuator 监控端点配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-admin-client.yml
  desc: SBA 客户端配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-admin-server.yml
  desc: SBA 服务端配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-druid.yml
  desc: Druid 多数据源配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-elasticsearch.yml
  desc: Elasticsearch 搜索引擎配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-logger.yml
  desc: 项目日志配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-minio.yml
  desc: Minio 文件系统配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-rabbitmq.yml
  desc: RabbitMQ 消息队列配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-redis.yml
  desc: Redis 缓存配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-sentinel.yml
  desc: Sentinel 限流熔断配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-token.yml
  desc: JWT Token 令牌配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: application-xxl-job.yml
  desc: XXL-JOB 分布式任务配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: tutor-admin.yml
  desc: Tutor Admin 专有配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: tutor-gateway.yml
  desc: Tutor Gateway 专有配置
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: tutor-support.yml
  desc: Tutor Support 专有配置
  group: DEFAULT_GROUP
  type: yaml