filebeat.inputs:
  - type: log
    paths:
      - /var/log/tutor/*.log
output.elasticsearch:
  hosts: [ "http://elasticsearch" ]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"