filebeat.inputs:
  - type: log
    paths:
      - /var/log/tutor/admin/*.log
      - /var/log/tutor/gateway/*.log
      - /var/log/tutor/support/*.log
output.elasticsearch:
  hosts: [ "http://elasticsearch:9200" ]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"