server.name: kibana
# Kibana 的主机地址 0.0.0.0 可表示监听所有 IP
server.host: "0.0.0.0"
# Kibana 访问 Elasticsearch 的 URL
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
#elasticsearch.username: 'elastic'
#elasticsearch.password: '123456'
# 显示登陆页面
xpack.monitoring.ui.container.elasticsearch.enabled: true
# 语言
i18n.locale: "zh-CN"