# Druid 多数据源配置
spring:
  datasource:
    dynamic:
      # 性能分析插件(有性能损耗，生产环境请关闭)
      p6spy: true
      # 多数据源配置（这里只配置了一个主数据源）
      datasource:
        # Druid 的统一配置
        druid:
          test-while-idle: true
          validation-query: SELECT 1
        # 主数据源的配置
        master:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/tutor?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
