# Sentinel 限流熔断配置
spring:
  cloud:
    sentinel:
      transport:
        dashboard: sentinel:8080
#      Nacos 持久化限流配置
#      datasource:
#        flow-rules:
#          nacos:
#            server-addr: nacos
#            data-id: sentinel-flow.json
#            rule-type: flow
#            namespace: 71ad7654-6ef6-4032-8da1-1b1cf3be1458