# CAS 单点登录配置
cas:
  # CAS 认证服务器的地址
  server-url-prefix: https://authserver.tjnu.edu.cn/authserver
  # CAS 认证服务器的登陆地址
  server-login-url: ${cas.server-url-prefix}/login
  # 客户端的主页地址
  client-host-url: https://tutor.tjnu.edu.cn
  # 不使用 Session 验证
  use-session: false
  # 校验之后不重定向
  redirect-after-validation: false
  # 开启 CAS 单点退出
  single-logout:
    enabled: true
  # CAS Ticket 校验类型
  validation-type: cas
  # 指定 CAS 断言中的属性名
  attribute-authorities: uid