# Sentinel 限流熔断配置
spring:
  cloud:
    sentinel:
      datasource:
        # Nacos 持久化限流配置
        flow-rules:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-flow.json
            rule-type: flow
            namespace: 71ad7654-6ef6-4032-8da1-1b1cf3be1458