# Tutor Admin 专有配置
# CAS 单点登录授权配置
cas:
  # 启用 CAS 授权功能
  enable: true
  # CAS 认证服务器相关地址
  server: http://localhost:8443/cas
  server-login-url: ${cas.server}/login
  server-logout-url: ${cas.server}/logout
  # 授权登陆地址
  service: http://localhost/auth/login
spring:
  # 关闭 Thymeleaf 的一些警告
  thymeleaf:
    check-template: false
    check-template-location: false