# Tutor Gateway 专有配置
security:
  # 开启 XSS 防御
  xss:
    enable: true
    excludeUrls:
      - /login
      - /logout
spring:
  cloud:
    gateway:
      # 资源跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      # 路由转发规则
      routes:
        - id: tutor-support-router
          uri: lb://tutor-support
          predicates:
            - Header=Authorization, Bearer .+
        - id: tutor-auth-router
          uri: lb://tutor-admin
          predicates:
            - Path=/login,/logout
          filters:
            - PrefixPath=/auth